
model = Sequential()
model.add(Convolution2D(32, 3, 3, input_shape=(16, 32, 3)))
# print('conv 1', model.output_shape)
# Max pooling will cut your shape in 1/2
model.add(MaxPooling2D((2, 2), dim_ordering='tf'))
# print('conv1 pool',model.output_shape)
model.add(Dropout(0.5))
# print('conv1 dropout',model.output_shape)
model.add(Activation('relu'))
# print('conv1 activation', model.output_shape)
model.add(Flatten())
# print('Flatten', model.output_shape)
model.add(Dense(128))
# print('FC1',model.output_shape)
model.add(Activation('relu'))
# print('FC1 Activation',model.output_shape)
model.add(Dense(1))
# print('FC2',model.output_shape)
#model.add(Activation('softmax'))
#print('FC 2 activation',model.output_shape)
